# Generated by Django 3.1.3 on 2021-01-16 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='fav',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.FileField(upload_to='Songs'),
        ),
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.IntegerField(verbose_name=((0, 'happy'), (1, 'angry'), (2, 'sad'), (3, 'neutral'), (4, 'general'))),
        ),
        migrations.AlterField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
